# Generated by Django 2.2.3 on 2019-10-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
